# vim: filetype=ruby
# vim: sts=2 ts=2 sw=2 et

#
# docker run -d --name=dev-consul -e CONSUL_BIND_INTERFACE=eth0 consul
# docker run -d -e CONSUL_BIND_INTERFACE=eth0 consul agent -dev -join=172.17.0.2
# docker run -d -e CONSUL_BIND_INTERFACE=eth0 consul agent -dev -join=172.17.0.2
# docker run -d --net=host -e 'CONSUL_ALLOW_PRIVILEGED_PORTS=' consul -dns-port=53 -recursor=8.8.8.8
#
# aweber/rabbitmq-autocluster:0.9.0
#

Vagrant.configure("2") do |config|
  config.vm.provider :docker do |d|
    d.compose = true
    d.image = 'aweber/rabbitmq-autocluster:0.9.0'
    d.name = 'horiga_tomtar'
    d.expose = [15672, 5672, 5671, 15671]
    d.env = {
        "AUTOCLUSTER_TYPE" => "consul",
        "AUTOCLUSTER_DELAY" => 60,
        "TCP_PORTS" => "15672, 5672",
        "CONSUL_HOST" => "consul",
        "CONSUL_SVC_ADDR_AUTO" => true,
        "AUTOCLUSTER_CLEANUP" => true,
        "CLEANUP_WARN_ONLY" => false,
        "CONSUL_DEREGISTER_AFTER" => 60
    }
    d.link("harry:haproxy")
  end

  config.vm.provider :docker do |d|
    d.compose = true
    d.image = 'dockercloud/haproxy'
    d.name = 'haproxy'
    d.ports = [ "15672:15672","5672:5672" ]
    d.env = {
      "MODE" => "tcp"
    }
    d.link("rabbitmq:haproxy")
  end

  # config.vm.box  =>  "bento/centos-7.3"
end
