---
- name: Install bintraybintray-rabbitmq-rabbitmq-server-rpm
  yum_repository:
    description: packages by rabbitmq from Bintray
    name: bintraybintray-rabbitmq-rabbitmq-server-rpm
    baseurl: https://dl.bintray.com/rabbitmq/rabbitmq-server-rpm
    gpgcheck: yes
    gpgkey: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
    enabled: yes
  register: repo_status
